apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ecommerce
type: Opaque
data:
  # Note: In production, these values should be populated by a secret management system
  # These are base64 encoded placeholders
  host: ${DB_HOST_BASE64}
  port: ${DB_PORT_BASE64}
  dbname: ${DB_NAME_BASE64}
  username: ${DB_USER_BASE64}
  password: ${DB_PASSWORD_BASE64} 